server:
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 5001

db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/marquez
  user: marquez
  password: marquez
  initialSize: 5
  minSize: 5
  maxSize: 20
  validationQuery: SELECT 1
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1s

logging:
  level: INFO
  appenders:
    - type: console
